create table authorities (
       authority varchar(11) not null,
        username varchar(255),
        primary key (authority)
    );

create table group_authorities (
       authority varchar(11) not null,
        group_id bigint,
        primary key (authority)
    );
    
create table group_members (
       id bigint generated by default as identity,
        group_id bigint,
        username varchar(255),
        primary key (id)
    );
    
create table groups (
       id bigint generated by default as identity,
        group_name varchar(255),
        primary key (id)
    );
    
create table users (
       username varchar(255) not null,
        enabled boolean,
        password varchar(255),
        primary key (username)
    );
    
alter table authorities 
       add constraint FK_AUTHORITIES__USERNAME 
       foreign key (username) 
       references users;
       
alter table group_authorities 
       add constraint FK_GROUP_AUTHORITIES__GROUP_ID 
       foreign key (group_id) 
       references groups;
       
alter table group_members 
       add constraint FK_GROUP_MEMBERS__GROUP_ID 
       foreign key (group_id) 
       references groups;
       
alter table group_members 
       add constraint FK_GROUP_MEMBERS__USERNAME 
       foreign key (username) 
       references users;