SELECT DISTINCT 
	a.MARKET,
	a.STOCK,
	a.CUSTOMER
FROM
	VIEWHISTORY a ORDER BY a.MARKET, a.STOCK, a.CUSTOMER;

SELECT b.MARKET, b.STOCK, c.MARKET, c.STOCK, COUNT(c.STOCK) count_stock
FROM
(SELECT DISTINCT 
	a.MARKET,
	a.STOCK,
	a.CUSTOMER
FROM
	VIEWHISTORY a) b LEFT JOIN  (SELECT DISTINCT 
	a.MARKET,
	a.STOCK,
	a.CUSTOMER
FROM
	VIEWHISTORY a) c ON b.CUSTOMER = c.CUSTOMER AND b.STOCK <> c.STOCK
GROUP BY b.MARKET, b.STOCK, c.MARKET, c.STOCK
ORDER BY b.MARKET, b.STOCK, count_stock desc, c.MARKET;

SELECT b.MARKET, b.STOCK, c.MARKET, c.STOCK, COUNT(c.STOCK) count_stock
FROM
(SELECT DISTINCT 
	a.MARKET,
	a.STOCK,
	a.CUSTOMER
FROM
	VIEWHISTORY a) b LEFT JOIN  VIEWHISTORY c ON b.CUSTOMER = c.CUSTOMER AND b.STOCK <> c.STOCK
GROUP BY b.MARKET, b.STOCK, c.MARKET, c.STOCK
ORDER BY b.MARKET, b.STOCK, count_stock desc, c.MARKET;


CREATE VIEW V_VIEW_HISTORY SELECT DISTINCT FROM VIEW_HISTORY

CREATE TABLE VIEW_HISTORY AS SELECT * FROM VIEWHISTORY ;

DROP TABLE APP.VIEW_HISTORY;

CREATE TABLE APP.VIEW_HISTORY (
	ID INTEGER NOT NULL,
	CUSTOMER INTEGER NOT NULL,
	MARKET VARCHAR(10) NOT NULL,
	STOCK VARCHAR(10) NOT NULL,
	INSERT_DATE DATE NOT NULL,
	CONSTRAINT VIEW_HISTORY_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX VIEW_HISTORY_PK ON APP.VIEW_HISTORY (ID);

INSERT INTO VIEW_HISTORY SELECT * FROM VIEWHISTORY;
